### PR TITLE
Add "base url" setter

### PR DESCRIPTION
**Pull request by kwn**
Sometimes it might be useful to set up the base url for client, especially if you register a client from within a dependency injection container. I would suggest to merge that feature into your repository and bump a version of the package.

It doesn't break the API of the `Client` class.

### CODE REVIEW

**Comment by KhristenkoYura** [comment]
thanks

**Comment by kwn** [comment]
@KhristenkoYura 

Thanks for merging my PR. Could you also consider creating a 3.1.0 tag (bump minor version as it has a new feature, and I believe you're following a semantic versioning)? 

Thanks.

**Comment by KhristenkoYura** [comment]
https://github.com/KhristenkoYura/mcurl/releases/tag/3.1.0

**Comment by kwn** [comment]
Thank you!

**Pull request merged**
