### PR TITLE
Update client.php

### PR DESCRIPTION
**Pull request by gamebak**
Added completed function, to signal to client when curl finished processing all the requests.
It is pretty useful in case you are running asynchronously multiple requests and you want to know when curl finished.

...
function finished() {
    echo 'finished execution';
}

$client->completed('finished');

### CODE REVIEW

**Comment by KhristenkoYura** [comment]
Thank you for your interest in the code.
But I do not see the point in this function. To check the download is complete, you can use the function: $ client->has() or; $ client->all();

**Comment by gamebak** [comment]
Thanks for the answer, but I think you are missing the point of what I am trying to cover: 
has() may return after first async result, because it just checks if the result isn't empty and all() wiil fill your buffer with results data ( when you work with over 100k results, that's not an option )

I think there may be others like me that turned to reactphp to work with big data, in my case I am doing 250k proxies in async, so all() and has() aren't an option.

**Comment by agd-stack** [comment]
KhristenkoYura,   addCurlOption() do not working?

**Comment by KhristenkoYura** [comment]
lapuh, use function ->setCurlOption()

**Comment by KhristenkoYura** [comment]
For react-php use component https://github.com/KhristenkoYura/reactphp-curl . There pull request will be relevant.
The beauty component mcurl that you can write code in sequence, without separating the context of a request from the addition of a response.
To handle the large number of requests, use an example from the documentation https://github.com/KhristenkoYura/mcurl#dynamic-add-request . And do not forget to monitor parameters such as:
-> setMaxRequest()
-> getCountQuery()

**Comment by gamebak** [comment]
Thanks for insight ! :+1:

**Pull request closed without merging**
